
[START_KEY]: 0x00;
;[TERMINATE_KEY]: 0x02;
[KEY_MODE]: 0x03;
[UIEE]: 0x01;
[EIBL]: 0x01;
[IGNORE_KEYLOCK]: 0x00;
;[EXT_MODE]: 0x01;
[ICON00]: 1.PNG
[ICON01]: 2.PNG
[ICON02]: 3.png
[ICON03]: 4.png

Desktop: Главное меню
FlashDesktopBook: Flash-меню
CUIDisplayableBook: JAVA-Приложение
StandbyBook: Режим ожидания
SimToolkitBook: Сим меню
VoiceMail UI Book: Голос. почта
SMS UI Book: Настройка SMS
MMS UI Book: Настройка MMS
CB UI Book: Инф. сообщения
WAP_Push UI Book: Извещения
Wv Buddy list book: Мои друзья
WAPCreateProfileBook: Создать профиль WAP
Menu_Globals: Главное меню
PB_UI_CallListBookObj_t: Вызовы
SMSViewer Book: Просмотр СМС
Session book: Текущее...
DataBrowserBook: Дисп. Файлов
CameraBook: Камера
PBContactsBook: Контакты
AudioPlayerBook: Walkman
FmRadio_Book: Радио
CaleBook: Календарь
DataBrowserCategoryListBook: Дисп. Файлов
MSG UI Book: Сообщения
NotesBook: Заметки
TimerBook: Таймер
StopWatchBook: Секундомер
SetBook: Меню
AddSelectProfile: Профили
ProfileBook: Профили
SoundRecorderBook: Запись звука
HIDBook: HID
MIDIComposerBook: Music DJ
PictureEditorBook: Photo DJ
VideoDJ_Book: Video DJ
SMS Editor Book: Редакт. SMS
SMS UI Book: Инф.
BrowserItemBook: Инф.
ShortcutBook: Ссылки
GoMusicBook: Клавиша Music
UILocksBook: Блокировки
TipsTricksBook: Советы
InternetAccountBook: Настр. Интернет
ImageViewerBook: Просмотр изображения
MediaPlayer_Video_Book: Просмотр видео
NetworkBook: Сотовые сети
BluetoothBook: Меню Bluetooth
PB_UI_call_bk: Звонки
SSBook: Меню
SessionBook: Приложение
ObExSendBook: Приём/Передача...
PBContactFormBook: Новый контакт
SendFileBook: Передать
MOCallBook: Глс. вызов
pb_ui_speeddial_bk: Быстрый набор
PBBook: Вызовы
ServiceMenuBook: Инженерное меню
WAP Browser Book: Интернет услуги
BooKManager: Уровень звука
InitBook: Меню запуска
PinBook: Ввод PIN
OnOffAnimationBook: Анимация
ObExReceiveBook: Передача файлов
MessageBoxBook: Предупреждение
KeylockBook: Блок. клавиатуры
WV Login book: Регистрация в сети
WV Buddy list book: Мои друзья
WV settings book: Парам. уч. записи
WV Add contact book: Добав. контакт
WV edit presence book: Мое состояние
Browser Book: Веб-браузер
ConnectionManagerBook: Менеджер Соединений
MM_BrowserToplevelBook: Walkman
Email Client Book: Эл. Почта

[ES_KEY1] /Icb_v1.elf
[EL_KEY1] /GraphicClock.elf
[ES_KEY2] /ScreenShooter.elf
[ES_KEY3] /flashlight6.elf
[ES_KEY5] /systemtemp_main.elf 
[EL_KEY0] /FileManager.elf 
[EL_KEY8] /KeyLogger_v3.0.elf 
[ES_KEY6] /VideoMode_v10.elf 
[ES_KEY8] /all_key_vibra.elf 
[ES_KEY9] /MissedEventsReminder_v06.elf 
[EL_KEY9] /EventControlv1.6.elf 
[EL_KEY3] /Camera Drive Changer v1.00.elf 
